//Mengimpor font Geist dan Geist Mono dari Google Fonts menggunakan fitur Next.js
import { Geist, Geist_Mono } from "next/font/google";

// Mengimpor CSS global yang berlaku untuk seluruh halaman aplikasi
import "./globals.css";


//Inisialisasi font Geist untuk teks biasa
//variable: nama CSS variable yang akan digunakan pada className
//subsets: subset karakter yang akan didownload (latin = huruf A-Z, angka, simbol)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


//Inisialisasi font Geist Mono untuk teks monospaced
//Biasanya digunakan untuk teks seperti kode atau terminal
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


//Metadata halaman
//Digunakan untuk menentukan informasi halaman seperti judul tab browser dan deskripsi website
export const metadata = {
  title: "Create Next App", // Judul yang muncul di tab browser
  description: "Generated by create next app",
};


//RootLayout adalah layout utama aplikasi Next.js
//Semua halaman (misalnya page.js) akan dibungkus oleh komponen ini
//children berisi konten halaman yang sedang ditampilkan
export default function RootLayout({ children }) {
  return (

    //Tag HTML sebagai root element halaman
    <html lang="en">

      {/*Tag body tempat seluruh isi halaman ditampilkan */}
      {/*className digunakan untuk menerapkan font yang sudah diinisialisasi */}
      {/*antialiased digunakan agar teks terlihat lebih halus di layar */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        {/*children adalah tempat konten halaman (misalnya page.js) dirender */}
        {children}

      </body>
    </html>
  );
}